<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Курсы валют'); ?>

        <!-- Styles -->
        <?php echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile(
                $this->basePath()
                . '/js/angular.min.js'
            );
        ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
    </body>
</html>
