<?php
$this->headScript()
    ->appendFile(
        $this->basePath()
        . '/js/rates.js'
);
?>

<div id="rates" class="well" ng-app="Rates" ng-controller="DefaultController">
    <div class="panel panel-default">
        <div class="panel-heading">
            Курсы валют на <?=date('d.m.Y')?>:
        </div>

        <table class="table" ng-init="getRates()">
            <tr ng-repeat="rate in rates.visible">
                <td>{{rate.abbreviation}}</td>
                <td>{{rate.nominal}}</td>
                <td>{{rate.name_ru}}</td>
                <td>{{rate.value}}</td>
                <td><button ng-click="hide(rate)">Не отображать</button></td>
            </tr>
        </table>
    </div>
    <div class="other-rates" ng-init="getTimeToEndOfDay()">
        Отобразить другие курсы валют:<br>
        <span ng-repeat="rate in rates.invisible">
            <a href="javascript: void(0)" ng-click="show(rate)">{{rate.name_ru}}</a>
        </span>
    </div>
</div>